config/routes.rb
Rails.application.routes.draw do
  devise_for :members
  devise_for :admins

  resources :galleries do
    resources :images, only: %i[new create]
  end

  resources :images, only: %i[index edit show update destroy]

  root to: 'home#index'

  get 'members/invitation/invite_members/:id' => 'invites#resend', as: 'invite_member_id'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
         include DeviseInvitable::Inviter

  has_many :galleries, dependent: :destroy, as: :owner
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  belongs_to :owner, polymorphic: true
  has_many :images, dependent: :destroy

  def default_image
    images.first || images.build
  end

end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :gallery

 has_attached_file :file, styles: { large: "600x600>", medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :file, content_type: /\Aimage\/.*\Z/
end

app/models/member.rb
class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable,
         resend_invitation:true

  has_many :galleries, dependent: :destroy, as: :owner

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  before_filter :set_host_from_request

  protected
  def authenticate_inviter!
    authenticate_admin!(:force => true)
  end

  private
  def set_host_from_request
    ActionMailer::Base.default_url_options = { host: request.host_with_port }
  end


  protected
  def configure_permitted_parameters
    # Only add some parameters
    devise_parameter_sanitizer.for(:accept_invitation).concat [:first_name, :last_name, :phone]
    # Override accepted parameters
    devise_parameter_sanitizer.for(:accept_invitation) do |u|
      u.permit(:first_name, :last_name, :phone, :password, :password_confirmation,
               :invitation_token)
    end
  end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :authenticate_member!

  # GET /galleries
  # GET /galleries.json
  def index
    @galleries = Gallery.all
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show
    @gallery = Gallery.find(params[:id])
  end

  # GET /galleries/new
  def new
    @gallery = current_member.galleries.build
  end

  # GET /galleries/1/edit
  def edit
    @gallery = Gallery.find(params[:id])
  end

  # POST /galleries
  def create
    @gallery = current_member.galleries.build(gallery_params)

    if @gallery.save
      redirect_to @gallery, notice: 'Gallery was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /galleries/1
  # PATCH/PUT /galleries/1.json
  def update
    @gallery = Gallery.find(params[:id])
    if @gallery.update(gallery_params)
        redirect_to @gallery, notice: 'Gallery was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @gallery = Gallery.find(params[:id])
    @gallery.destroy
      redirect_to galleries_url, notice: 'Gallery was successfully destroyed.'
  end

private

  # Never trust parameters from the scary internet, only allow the white list through.
  def gallery_params
    params.require(:gallery).permit(:name, :owner_id, :owner_type, :description, :avatar)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  def index
    @images = Image.all
  end

  def show
    image
  end

  def new
    @image = gallery.images.build
    end

  def edit
    image
  end

  # POST /images
  def create
    @image = gallery.images.new(image_params)

    if @image.save
      redirect_to @image.gallery, notice: 'Image was successfully created.'
    else
      render :new
    end
  end

  def update
    if image.update(image_params)
      redirect_to @image.gallery, notice: 'Image was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    image.destroy
    redirect_to images_url, notice: 'Image was successfully destroyed.'
  end

private

  def gallery
    @gallery ||= Gallery.find(params[:gallery_id])
  end

  def image
    @image ||= Image.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def image_params
    params.require(:image).permit(:name, :description, :file)
  end

end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  def resend
    @member = Member.find(params[:id])
    @member.invite!
    redirect_to galleries_url, notice: 'Re-sent Confirmation Successfully!'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/helpers/members/galleries_helper.rb
module Members::GalleriesHelper
end

app/helpers/resend_invitation_helper.rb
module ResendInvitationHelper
end

app/views/application/_menu.html.erb
<% if member_signed_in? %>

  <%= link_to 'Logout', destroy_member_session_path, class:"btn btn-default navbar-btn", method: :delete %>

  <%= link_to "Galleries", galleries_path, class:"btn btn-default navbar-btn" %>

  <%= link_to "Home", root_path, class: "btn btn-default navbar-btn" %>

<% else %>
  <%= link_to "Login", new_member_session_path, class:"btn btn-default navbar-btn" %>

<% end %>

app/views/galleries/_form.html.erb
<%= form_for @gallery, html: { multipart: true } do |f| %>
  <% if @gallery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>

      <ul>
        <% @gallery.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class:"form-control"  %>
  </div>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class:"form-control" %>
  </div>


<br/>

  <div class="actions">
    <%= f.submit 'Submit', class: "btn btn-primary" %>
  </div>
  <br/>
<% end %>

app/views/galleries/_gallery_card.html.erb
<div class = "box">

  <div class="thumbnail">

    <div class = "panel-body">
      <%= link_to image_tag(gallery_card.default_image.file.url(:medium),
                            :class => "img-responsive"), gallery_card %><br/>

                            <strong><%= gallery_card.description %><br/></strong>
                            <em><%= gallery_card.name if gallery_card.name %><br/></em>
    </div>

    <div class="btn-group btn-group-justified" >
      <div class = "btn-group">
        <%= link_to 'Edit', edit_gallery_path(gallery_card), :class => "btn btn-info active" %>
      </div>


      <div class = "btn-group">
        <%= link_to 'Destroy', gallery_card, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-default" %> <br/>
      </div>


    </div>
  </div>
</div>

app/views/galleries/edit.html.erb
<h1>Editing Gallery</h1>

<%= render 'form' %>

<%= link_to 'Show', @gallery %> |
<%= link_to 'Back', galleries_path %>

app/views/galleries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Galleries</h1>

<div id='album' class = 'transitions-enabled'>
  <%= render partial: 'gallery_card', collection: @galleries %>
</div>

app/views/galleries/new.html.erb
<br/>
<%= link_to 'Back', galleries_path %>

<h1>New Gallery</h1>

<%= render 'form' %>

app/views/galleries/show.html.erb
  <div class="row">
    <%= render partial: "/images/image", collection: @gallery.images, locals: { size: :medium } %>
    <% render partial: "/images/new_image" %>
  </div>


  <%= link_to "Add Image", new_gallery_image_path(params[:id]), class:"btn btn-primary btn-block active" %>

app/views/home/index.html.erb
<div class="jumbotron" id="jumbo">

  <h1>Family Album</h1>
  <p>Family source for sharing pictures!</p>

</div>

app/views/images/_form.html.erb
<%= form_for([@gallery, @image], html: { multipart: true }) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.file_field :file %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/_image.html.erb
    <%= link_to image_tag(image.file.url(size)), image %>

app/views/images/_new_image.html.erb
<%= link_to new_gallery_image_path(params[:id]) do %>
  <%= image_tag asset_path("images/medium/new_image.png") %>
<% end %>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Images</h1>

<table>
  <thead>
    <tr>
      <th>Gallery</th>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.gallery %></td>
        <td><%= image.name %></td>
        <td><%= image.description %></td>
        <td><%= link_to 'Show', image %></td>
        <td><%= link_to 'Edit', edit_image_path(image) %></td>
        <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form' %>
<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
  <%= render partial: "image", object: @image, locals: { size: :large } %>

  <%= @image.description %>

  <%= link_to 'Back to gallery' , @image.gallery %>

app/views/invites/new.html.erb
<%= form_for @invite do |f| %>

  <%= f.text_field :email %>
  <%= f.text_field :name %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FamilyGallery</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body> 

    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-success") %>
    <% end %>

    <div class="container">

      <%= render "menu" %>
      <%= yield %>

    </div>

    <%= javascript_include_tag 'application'%>

  </body>
</html>

app/views/member/galleries/_form.html.erb
<%= form_for(@gallery) do |f| %>
  <% if @gallery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>

      <ul>
      <% @gallery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :owner_id %><br>
    <%= f.text_field :owner_id %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/members/invitations/edit.html.erb
<h2><%= t 'devise.invitations.edit.header' %></h2>

<%= form_for resource, :as => resource_name, :url => invitation_path(resource_name), :html => { :method => :put } do |f| %>
  <%= devise_error_messages! %>
  <%= f.hidden_field :invitation_token %>

  <p><%= f.label :password %><br />
  <%= f.password_field :password %></p>

  <p><%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %></p>

  <p><%= f.submit t("devise.invitations.edit.submit_button") %></p>
<% end %>

app/views/members/invitations/new.html.erb
<h2><%= t "devise.invitations.new.header" %></h2>
<br>

<%= form_for resource, :as => resource_name, :url => invitation_path(resource_name), :html => {:method => :post} do |f| %>
  <%= devise_error_messages! %>

  <% resource.class.invite_key_fields.each do |field| -%>
    <p><%= f.label field %><br />
    <%= f.text_field field, :class =>"form-control" %></p>
  <% end -%>

  <%= f.submit t("devise.invitations.new.submit_button"), :class => "btn btn-primary"  %>
<% end %>

<br><br><br><br>

 <h4>Pending Approvals</h4>

<table class="table table-hover table table-striped">
  <% Member.invitation_not_accepted.each do |member| %>
    <tr>
      <td><%= member.email %></td>
      <td><%= member.id %>
      <td><%= link_to 'Re-send Invitation', invite_member_id_path(member.id),
        :class => "btn btn-default btn-xs active" %></td>
    </tr>
  <% end %>
</table>

app/views/resend_invitation/resend_invite.html.erb
<h1>ResendInvitation#resend_invite</h1>
<p>Find me in app/views/resend_invitation/resend_invite.html.erb</p>